### ISSUE TITLE
problem while using Editext-mask in Dialog Fragment.

### ISSUE THREAD

**Issue by jazzbpn** [egslava/edittext-mask#36]
Process: com.vivekahealth.vivekahealth, PID: 15080
                                                                               android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class br.com.sapereaude.maskedEditText.MaskedEditText
                                                                               Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class br.com.sapereaude.maskedEditText.MaskedEditText
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                   at com.vivekahealth.vivekahealth.login.fragment.FragmentContinueAsGuest.onCreateView(FragmentContinueAsGuest.java:95)
                                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                                   at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                                   at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                                   at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                                   at android.os.Handler.handleCallback(Handler.java:836)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                   at android.os.Looper.loop(Looper.java:232)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6661)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1106)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by MatheusPimentel** [comment]
I have the same problem

**Comment by kovac777** [comment]
This is because you don't set 'mask' property in xml layout file
