### ISSUE TITLE
Doesn't work with androidx?

### ISSUE THREAD

**Issue by fauzynurn** [egslava/edittext-mask#50]
I'm trying to use the sample code shown below : 

`<br.com.sapereaude.maskedEditText.MaskedEditText
    android:id="@+id/phone_input"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:inputType="phone"
    android:typeface="monospace"
    mask:allowed_chars="1234567890"
    mask:mask="+7(###)###-##-##"
    android:hint="1234567890"
    app:keep_hint="true"
    /> `

but it always give me this error : 
`android.view.InflateException: Binary XML file line #64: Binary XML file line #64: Error inflating class br.com.sapereaude.maskedEditText.MaskedEditText
    Caused by: android.view.InflateException: Binary XML file line #64: Error inflating class br.com.sapereaude.maskedEditText.MaskedEditText
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)`

I currently working with androidx, is this library has problems with androidx?

btw, nice library. Thanks!

**Comment by egslava** [comment]
Hey @fauzynurn! Could you, please, attach a minimal example for me to able to reproduce the problem?
